In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
import math
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [2]:
train_dataset = pd.read_csv("energy_train.csv")
test_dataset = pd.read_csv("energy_test.csv")

train_dataset = train_dataset.set_index("id")
test_dataset = test_dataset.set_index("id")
train_dataset.dropna(axis=0,  inplace=True)

In [3]:
train_dataset.columns = ['Date','WattHour', 'Lumin','D1','M1','D2','M2','D3','M3','D4','M4','D5','M5','D6','M6','D7','M7','D8','M8','D9','M9','D_Cout','Pressure','M_Cout','Wind','Clarity','Dew','R1','R2']

test_dataset.columns = ['Date', 'Lumin','D1','M1','D2','M2','D3','M3','D4','M4','D5','M5','D6','M6','D7','M7','D8','M8','D9','M9','D_Cout','Pressure','M_Cout','Wind','Clarity','Dew','R1','R2']

In [4]:
train_dataset.dropna(axis=0,inplace=True)
train_dataset['Lumin'] = train_dataset['Lumin'].astype(float)
test_dataset['Lumin'] = test_dataset['Lumin'].astype(float)
train_dataset.round(decimals=2)
test_dataset.round(decimals=2)
np.nan_to_num(train_dataset)
np.nan_to_num(test_dataset)
train_dataset.fillna("bfill")
test_dataset.fillna("bfill")
test_dataset

,Date,Lumin,D1,M1,D2,M2,D3,M3,D4,M4,...,D9,M9,D_Cout,Pressure,M_Cout,Wind,Clarity,Dew,R1,R2
id,,,,,,,,,,,,,,,,,,,,,
15001,2016-04-24 21:00:00,0.0,21.926667,35.500000,19.290000,37.500000,22.390000,34.000000,21.390000,32.225714,...,20.200000,NaN,4.100000,758.000000,82.000000,3.0,40.000000,1.200000,10.668196,10.668196
15002,2016-04-24 21:10:00,0.0,21.890000,35.400000,19.222500,37.425000,22.390000,34.090000,21.350000,32.200000,...,20.200000,32.400000,3.950000,758.050000,82.166667,3.0,40.000000,1.100000,48.467852,48.467852
15003,2016-04-24 21:20:00,0.0,21.890000,35.400000,19.200000,37.466667,22.390000,33.963333,21.290000,32.277143,...,20.200000,32.290000,3.800000,758.100000,82.333333,3.0,40.000000,1.000000,36.388536,36.388536
15004,2016-04-24 21:30:00,0.0,21.890000,35.400000,19.100000,37.590000,22.390000,33.900000,21.290000,32.334000,...,20.175000,32.290000,3.650000,758.150000,82.500000,3.0,40.000000,0.900000,17.198176,17.198176
15005,2016-04-24 21:40:00,0.0,21.890000,35.400000,19.100000,37.590000,22.390000,33.966667,21.290000,32.290000,...,20.166667,32.563333,3.500000,758.200000,82.666667,3.0,40.000000,0.800000,7.200588,7.200588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19371,2016-05-25 05:20:00,10.0,23.600000,40.833333,20.856667,43.566667,25.260000,39.266667,23.500000,39.000000,...,22.600000,44.790000,6.166667,757.133333,95.000000,1.0,24.666667,5.433333,43.792662,43.792662
19372,2016-05-25 05:30:00,0.0,23.666667,40.566667,20.790000,43.700000,25.133333,38.666667,23.500000,38.933333,...,22.600000,44.760000,6.150000,757.100000,95.500000,1.0,24.500000,5.500000,22.151890,22.151890
19373,2016-05-25 05:40:00,0.0,23.600000,40.093333,20.700000,43.296667,24.963333,37.833333,23.463333,38.563333,...,22.600000,44.760000,6.133333,757.066667,96.000000,1.0,24.333333,5.566667,5.759009,5.759009
19374,2016-05-25 05:50:00,0.0,23.600000,39.426667,20.633333,42.830000,24.823333,37.566667,23.390000,38.096667,...,22.600000,44.700000,6.116667,757.033333,96.500000,1.0,24.166667,5.633333,13.711184,13.711184
19375,2016-05-25 06:00:00,0.0,23.600000,39.026667,20.600000,42.333333,24.760000,36.930000,23.390000,38.000000,...,22.600000,44.626667,6.100000,757.000000,97.000000,1.0,24.000000,5.700000,45.858992,45.858992

In [24]:
X = train_dataset.drop(['WattHour','Date','D1','D2','D3','D4','D5','D6'], axis=1)
y = train_dataset["WattHour"]

In [25]:


from sklearn.model_selection import train_test_split
# here I used 20% data for test_data and 80% as train_data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [26]:
from sklearn.svm import SVR
regressor = SVR()

In [27]:
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [28]:
y_pred = regressor.predict(X_test)
# Printing the R^2 score
regressor.score(X_test, y_test)

-0.1254570664189778

In [29]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_pred, y_test)
print("Mean absolute error:", mae)

Mean absolute error: 57.446038703228226

In [30]:
from sklearn.model_selection import GridSearchCV
parameters = {'C':[0.01, 0.1], 'epsilon':[0.01, 0.1]}
regressor = SVR(verbose=2)
clf = GridSearchCV(regressor, parameters, cv=5)  # Here cv means cross validation sets(number of sets in which the data will be divided)
clf.fit(X_train, y_train)

[LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM]

GridSearchCV(cv=5, error_score=nan,
             estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3,
                           epsilon=0.1, gamma='scale', kernel='rbf',
                           max_iter=-1, shrinking=True, tol=0.001, verbose=2),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.01, 0.1], 'epsilon': [0.01, 0.1]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [31]:
regressor.fit(X, y)

[LibSVM]

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=2)

In [32]:
X = np.nan_to_num(test_dataset.drop(['Date','Lumin',], axis=1))
y_pred = regressor.predict(X)
y_pred = y_pred.astype(int)

ValueError: X.shape[1] = 26 should be equal to 21, the number of features at training time

In [15]:
y = pd.DataFrame({"WattHour":y_pred})

In [16]:
y.to_csv("aborules.csv",index=False)