In [12]:
import pandas as pd
import numpy as np

In [13]:
df  = pd.read_csv("TREE.csv")

In [14]:
df

,Region,Tree_Count,Median_Girth,Median_Girth_Low,Median_Girth_High,Median_Canopy,Median_Canopy_Low,Median_Canopy_High,Median_Height,Median_Height_Low,...,Tree_6,Tree_7,Tree_8,Tree_9,Tree_10,SO2,NOx,AQI,PM10,Other_Tree_Count
0,Karve Road,30618,0.60,15255,15363,4,14517,16101,7,14143,...,Cluster Fig Tree\t,Sonchapha\t,Neem,Jamun,\tIndian Cork Tree,14,37,97.5,96,30886
1,Nal Stop,25913,0.59,12814,13099,4,11987,13926,7,12354,...,Neem,Sonchapha,Cluster Fig Tree,Jamun,Silver Oak,40,82,123.0,133,110700
2,Swargate,21536,0.62,10693,10843,4,9673,11863,8,9762,...,Subabul\t,Neem,Pipal,Jamun,Sonchapha,36,94,117.0,95,779540

In [15]:
for i in df.columns[1:17]:
    
    x = df[i].corr(df['SO2'])
    y = df[i].corr(df['NOx'])
    z = df[i].corr(df['AQI'])
    a = df[i].corr(df['PM10'])
    b = df[i].corr(df['Other_Tree_Count'])
    print ("\n\n" + str(i) + "\n SO2: " + str(x) + " \n NOx: " + str(y) + "\n AQI: " + str(z) + "\n  PM10: " + str(a) + "\n Other Tree Count: " + str(b))

Tree_Count
 SO2: -0.7984390890220584
 NOx: -0.9548232181503891
 AQI: -0.7453666673628687
  PM10: 0.002241693750726003
 Other Tree Count: -0.9016489916252264


Median_Girth
 SO2: 0.04676097647914122
 NOx: 0.38124642583151164
 AQI: -0.036827146210517726
  PM10: -0.7708419944740396
 Other Tree Count: 0.9086773523953751


Median_Girth_Low
 SO2: -0.8101019062248965
 NOx: -0.9604717829300081
 AQI: -0.7583071668764382
  PM10: -0.01738514529941402
 Other Tree Count: -0.8929874919642162


Median_Girth_High
 SO2: -0.7863459864164725
 NOx: -0.9487440630173446
 AQI: -0.732003710531265
  PM10: 0.022066256809470598
 Other Tree Count: -0.9100454986662966


Median_Canopy
 SO2: nan
 NOx: nan
 AQI: nan
  PM10: nan
 Other Tree Count: nan


Median_Canopy_Low
 SO2: -0.8013742023812942
 NOx: -0.9562652343273661
 AQI: -0.7486182625191578
  PM10: -0.002649173268046004
 Other Tree Count: -0.8995230674759808


Median_Canopy_High
 SO2: -0.7950601583322332
 NOx: -0.9531466694310451
 AQI: -0.7416274780867715
  PM10: 0.007833051276224091
 Other Tree Count: -0.9040530048453811


Median_Height
 SO2: 0.37115374447904514
 NOx: 0.6628489803598703
 AQI: 0.2923064111077339
  PM10: -0.5198613887753597
 Other Tree Count: 0.9952780392809434


Median_Height_Low
 SO2: -0.716253690755617
 NOx: -0.9097930243541671
 AQI: -0.6554705193640049
  PM10: 0.12816738630637398
 Other Tree Count: -0.9489362598970285


Median_Height_High
 SO2: -0.863349290950481
 NOx: -0.9830170364387908
 AQI: -0.8181903177170776
  PM10: -0.11467714334199729
 Other Tree Count: -0.8449094017623529


Healthy
 SO2: -0.848210824020508
 NOx: -0.9772249043903445
 AQI: -0.8010124942967527
  PM10: -0.08555352129333907
 Other Tree Count: -0.8602029576160208


Average
 SO2: 0.022911222983168472
 NOx: -0.3159453862958625
 AQI: 0.10632537571152177
  PM10: 0.8133300564655
 Other Tree Count: -0.8773990905981232


Poor
 SO2: -0.9987001771606964
 NOx: -0.9228585945571102
 AQI: -0.9994679737136151
  PM10: -0.6402692126640026
 Other Tree Count: -0.4136660112746417


Dead
 SO2: -0.5489725295436416
 NOx: -0.7989219519087296
 AQI: -0.47724850928023416
  PM10: 0.3389545229919945
 Other Tree Count: -0.9946315789067626


Rare
 SO2: -0.7189670470619449
 NOx: -0.911403206518064
 AQI: -0.6584078931043417
  PM10: 0.1243025347013859
 Other Tree Count: -0.9476999916759001


Not_Rare
 SO2: -0.8085007973571263
 NOx: -0.959709417339477
 AQI: -0.7565274160934621
  PM10: -0.014659705368402054
 Other Tree Count: -0.8942110009317444